//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Delicious_Food.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public string adAcc { get; set; }
        public string adPass { get; set; }
        public string fullname { get; set; }
        public string gmail { get; set; }
        public string address { get; set; }
        public Nullable<decimal> adphone { get; set; }
        public Nullable<bool> adsex { get; set; }
        public string Imgtv { get; set; }
    }
}
